"""Initial migration.

Revision ID: 0293ea1a0430
Revises: 9d5f12822fd4
Create Date: 2023-02-14 17:25:18.465180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0293ea1a0430'
down_revision = '9d5f12822fd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('artist_name', sa.String(), nullable=True))
    op.add_column('Show', sa.Column('artist_image_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'artist_image_link')
    op.drop_column('Show', 'artist_name')
    # ### end Alembic commands ###
