"""Initial migration.

Revision ID: b0830d1829e4
Revises: 0293ea1a0430
Create Date: 2023-02-14 17:27:14.585594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0830d1829e4'
down_revision = '0293ea1a0430'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('venue_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'venue_name')
    # ### end Alembic commands ###
